# Generated by Django 4.2.7 on 2026-02-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20)),
                ('calories', models.IntegerField(default=0)),
                ('proteins', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('allergens', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast_items', models.ManyToManyField(limit_choices_to={'meal_type': 'breakfast'}, related_name='breakfast_menus', to='menu.dish')),
                ('lunch_items', models.ManyToManyField(limit_choices_to={'meal_type': 'lunch'}, related_name='lunch_menus', to='menu.dish')),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
